export default {
    getHomeData:()=>{
        return{
            code:200,
            data:{
                big_sort:[
                    {
                        name:"美食",
                        icon:"icon-meishi"
                    },
                    {
                        name:"甜点饮品",
                        icon:"icon-tiandian"
                    },
                    {
                        name:"超市便利",
                        icon:"icon-gouwu-2"
                    },
                    {
                        name:"生鲜果蔬",
                        icon:"icon-shucai"
                    },
                    {
                        name:"团买药",
                        icon:"icon--"
                    },
                ],
                small_sort:[
                    {
                        name:"午餐",
                        icon:"icon-wucan"
                    },
                    {
                        name:"买酒",
                        icon:"icon-jiu"
                    },
                    {
                        name:"新鲜水果",
                        icon:"icon-icon-test"
                    },
                    {
                        name:"汉堡披萨",
                        icon:"icon-hanbao"
                    },
                    {
                        name:"休闲饮品",
                        icon:"icon-xiuxianyinpin"
                    },
                    {
                        name:"夜宵",
                        icon:"icon-yexiao"
                    },
                    {
                        name:"蛋糕",
                        icon:"icon-dangao"
                    },
                    {
                        name:"跑腿",
                        icon:"icon-paotuiAPP"
                    },
                    {
                        name:"美妆",
                        icon:"icon-huazhuang"
                    },
                    {
                        name:"全部分类",
                        icon:"icon-quanbu"
                    },
                ],
                content_nav_list:[
                    {
                        tab:'天天神券',
                        data:[
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                        ]
                    },
                    {
                        tab:'减配送费',
                        data:[
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                        ]
                    },
                    {
                        tab:'点评高分',
                        data:[
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                        ]
                    },
                    {
                        tab:'会员满减',
                        data:[
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://img5.pxto.com.cn/n_21169409_5fa4e788bc81a.jpg",
                                title:"隆江猪脚饭",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                            {
                                pic:"https://5b0988e595225.cdn.sohucs.com/images/20200317/bf29a4f83eee4960af52417bcd56436c.png",
                                title:"酸菜鱼",
                                sales:"2888",
                                price:"2888",
                                label:["门店上新","很下饭"],
                            },
                        ]
                    },
                ]
            }
        }
    }
}